---
- name: Les Templates Jinja2
  hosts: all
  vars:
    stagiaires:
      - Alexandre
      - Hamza
      - Julio
      - Laury
      - Mohammed
      - Moussa
      - Rachid
      - Safia
      - Yassen
      - Yolande
    logins:
      - login: bob
        home: /home/bob
      - login: curt
        home: /home/curt

    bob:
      prenom: bob
      nom: léponge
      lieu: au fond de l'eau
  tasks:
  - name: Template
    template:
      src: data-2.txt.j2
      dest: /tmp/data.txt
